app/__init__.py
# Licensed Materials - Property of IBM
# 5725I71-CC011829
# (C) Copyright IBM Corp. 2015, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

__author__ = "IBM"

from packaging import version

import secrets  # For generating a new secret key
from flask_wtf.csrf import CSRFProtect  # To add CSRF protection
from qpylib.encdec import (
    Encryption,
    EncryptionError,
)  # To handle storing the secret key securely

from flask import Flask
from qpylib import qpylib, log_qpylib, __version__


def suppress_syslog():
    return None


# Flask application factory.
def create_app():
    # Create a Flask instance.
    qflask = Flask(__name__)

    csrf = CSRFProtect()
    csrf.init_app(qflask)

    # Generate or retrieve a secret key
    try:
        # Read in secret key
        secret_key_store = Encryption({"name": "secret_key", "user": "shared"})
        secret_key = secret_key_store.decrypt()
    except EncryptionError:
        # If secret key file doesn't exist/fail to decrypt it,
        # generate a new random password for it and encrypt it
        secret_key = secrets.token_urlsafe(64)
        secret_key_store = Encryption({"name": "secret_key", "user": "shared"})
        secret_key_store.encrypt(secret_key)

    qflask.config["SECRET_KEY"] = secret_key

    # Retrieve QRadar app id.
    qradar_app_id = qpylib.get_app_id()

    # Create unique session cookie name for this app.
    qflask.config["SESSION_COOKIE_NAME"] = "session_{0}".format(qradar_app_id)

    # Hide server details in endpoint responses.
    # pylint: disable=unused-variable
    @qflask.after_request
    def obscure_server_header(resp):
        resp.headers["Server"] = "QRadar App {0}".format(qradar_app_id)
        return resp

    # Register q_url_for function for use with Jinja2 templates.
    qflask.add_template_global(qpylib.q_url_for, "q_url_for")

    # Initialize logging.
    if version.parse(__version__) >= version.parse("2.0.5"):
        qpylib.create_log(False)
    else:
        log_qpylib._get_address_for_syslog = suppress_syslog
        qpylib.create_log()

    # To enable app health checking, the QRadar App Framework
    # requires every Flask app to define a /debug endpoint.
    # The endpoint function should contain a trivial implementation
    # that returns a simple confirmation response message.
    @qflask.route("/debug")
    def debug():
        return "Pong!"

    # Import additional endpoints.
    # For more information see:
    #   https://flask.palletsprojects.com/en/1.1.x/tutorial/views
    from . import views

    qflask.register_blueprint(views.viewsbp)
    from . import dev

    qflask.register_blueprint(dev.devbp)

    return qflask

app/views.py
# Licensed Materials - Property of IBM
# 5725I71-CC011829
# (C) Copyright IBM Corp. 2015, 2020. All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

import ipaddress
import requests


from flask import (
    Blueprint,
    render_template,
    current_app,
    send_from_directory,
    request,
    redirect,
    jsonify,
    abort,
)
from qpylib.encdec import Encryption
from qpylib import qpylib

# pylint: disable=invalid-name

viewsbp = Blueprint("viewsbp", __name__, url_prefix="/")
SecretStore = Encryption({"name": "crowdsec_config", "user": "crowdsec"})


def get_api_key():
    try:
        return SecretStore.decrypt()
    except:
        return ""


# The presence of this endpoint avoids a Flask error being logged when a browser
# makes a favicon.ico request. It demonstrates use of send_from_directory
# and current_app.
@viewsbp.route("/favicon.ico")
def favicon():
    return send_from_directory(current_app.static_folder, "favicon-16x16.png")


@viewsbp.route("/updateConfig", methods=["POST"])
def update_config():
    api_key = request.form["api-key"]
    SecretStore.encrypt(api_key)
    return redirect(qpylib.q_url_for("viewsbp.config"), code=303)


@viewsbp.route("/config")
def config():
    """Render app configuration page."""
    api_key = "*" * len(get_api_key())
    return render_template("config.html", api_key=api_key)


@viewsbp.route("/right_click_ip", methods=["GET"])
def right_click_ip():
    ip = request.args.get("context")
    try:
        ipaddress.ip_address(ip)
    except Exception as e:
        return abort(500)

    return jsonify({"ip": ip, "base_url": qpylib.get_app_base_url()})


@viewsbp.route("/smoke")
def lookup_in_smoke():
    ip = request.args.get("context")
    api_key = get_api_key()
    resp = requests.get(
        f"https://cti.api.crowdsec.net/v2/smoke/{ip}",
        headers={
            "x-api-key": api_key,
            "User-Agent": "crowdsec-qradar/v1.0.0",
        },
    )
    try:
        resp.raise_for_status()
    except Exception as e:
        error_msg = str(e)[3:]
        if resp.status_code == 429:
            error_msg = "Quota exceeded for CrowdSec CTI API. Please visit https://www.crowdsec.net/pricing to upgrade your plan."
        return render_template(
            "error.html",
            ip=(ip),
            error_msg=error_msg,
            status=str(e)[:3],
            api_resp=resp.json(),
        )
    return render_template("smoke.html", data=resp.json())

app/templates/config.html
<!DOCTYPE html>
<html>
  <head>
    <title>Enter Your API Key</title>
    <link rel="preconnect" href="{{ q_get_app_base_url }}" crossorigin>
    <link rel="preload" href="{{ q_get_app_base_url }}static/fonts/Montserrat-Regular.ttf" as="font" type="font/ttf" crossorigin>
    <style>
      body {
        background-color: #1f2937;
        color: #f8f9fa;
        font-family: 'Montserrat', sans-serif;
        font-size: 16px;
        line-height: 1.5;
        margin: 0;
        padding: 0;
      }
      @font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('{{ q_get_app_base_url }}static/fonts/Montserrat-Regular.ttf') ;
}
     

      .navbar {
        background-color: #111827;
        height: 60px;
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 0 20px;
        position: relative;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
      }
      .navbar-left {
        display: flex;
        align-items: center;
      }
      .navbar::after {
			content: "";
			position: absolute;
			bottom: 0;
			left: 0;
			width: 100%;
			height: 2px;
			background-color: #252f3e;
		}
      .navbar-logo {
        height: 40px;
        width: auto;
      }

      h1 {
        font-size: 2rem;
        font-weight: bold;
        margin-top: 3rem;
        margin-bottom: 2rem;
        text-align: center;
      }

      form {
        max-width: 500px;
        margin: 0 auto;
      }

      label {
        display: block;
        margin-bottom: 0.5rem;
        font-weight: bold;
      }

      input[type="text"] {
        display: block;
        width: 100%;
        max-width: -webkit-fill-available;
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        line-height: 1.5;
        color: #f8f9fa;
        background-color: #343a40;
        background-clip: padding-box;
        border: 1px solid #f8f9fa;
        border-radius: 0.25rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
      }

      input[type="text"]:focus {
        border-color: #80bdff;
        box-shadow: 0 0 0 0.2rem rgba(128, 189, 255, 0.25);
      }

      button[type="submit"] {
        display: block;
        margin-top: 1rem;
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #212529;
        background-color: rgb(155, 24, 188);
        background-image: none;
        border: 1px solid rgb(155, 24, 188);
        border-radius: 0.25rem;
        transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out,
          box-shadow 0.15s ease-in-out;
        cursor: pointer;
      }

      button[type="submit"]:hover {
        color: #212529;
        background-color: #918bca;
        border-color: #918bca;
        box-shadow: 0 0 0 0.2rem #918bca;
      }
    </style>
  </head>
  <body>

    <header>
      <nav class="navbar">
        <div class="navbar-left">
          <img class="navbar-logo" src="{{ q_get_app_base_url }}static/crowdseclogo.png" alt="Logo" />
          <!-- <span class="forward-slash" style="font-size:35px ; color:#595f6a;margin-left: 5px;"> /</span> -->
          <b>
            <span class="navbar-ip" id="navd"></span>
        </div>
      </nav>
      
    </header>
    <main>
      <h1>Enter Your API Key</h1>
      <form id="api-key-form" action="{{ q_url_for('viewsbp.update_config') }}" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div style="margin-bottom: 0.5rem;">
          <label for="api-key">API Key</label>
          <input type="text" pattern=".{35,}" required title="35 characters minimum" id="api-key" name="api-key" placeholder="{{api_key}}">
        </div>
        <button type="submit">Submit</button>
      </form>
    </main>
  </body>
</html>

app/templates/error.html
<!DOCTYPE html>
<html>
  <head>
    <title>Error</title>
    <!-- <link rel="stylesheet" href="{{ q_get_app_base_url }}static/gfonts.css"> -->
    <!-- Custom styles for dark theme -->

    <link rel="preconnect" href="{{ q_get_app_base_url }}" crossorigin>
    <link rel="preload" href="{{ q_get_app_base_url }}static/fonts/Montserrat-Regular.ttf" as="font" type="font/ttf" crossorigin>

    <style>
      body {
        background-color: #1f2937;
        color: #f8f9fa;
        font-family: 'Montserrat', sans-serif;
        font-size: 16px;
        line-height: 1.5;
        margin: 0;
        padding: 0;
      }
      @font-face {
  font-family: 'Montserrat';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('{{ q_get_app_base_url }}static/fonts/Montserrat-Regular.ttf');
}

      .navbar {
        background-color: #111827;
        height: 60px;
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 0 20px;
        box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.5);
      }

      .navbar-logo {
        height: 40px;
        width: auto;
      }

      .navbar-ip {
        margin-left: 10px;
        font-size: 25px;
      }

      .navbar-left {
        display: flex;
        align-items: center;
      }

      .popup {
        display: none;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        padding: 30px;
        background-color: #1f2937;
        border-radius: 3mm;
        border: 1px solid #ccc;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
        z-index: 9999;
        text-align: center;
        width: 72%;
        height: 25%;
        overflow: auto;
        max-width: 100%;
        max-height: 100%;
      }

      .popup::-webkit-scrollbar {
        width: 0px;
        background-color: transparent #918bca;
        /* border-radius: px; */
      }

      .popup::-webkit-scrollbar-thumb {
        width: 0px;
        height: 0 px;
        background-color: transparent #918bca;
        /* border-radius: 4px; */
      }
    </style>
  </head>
  <body onload="document.getElementById('popup').style.display='block'">
    <header>
      <nav class="navbar">
        <div class="navbar-left">
          <img class="navbar-logo" src="{{ q_get_app_base_url }}static/crowdseclogo.png" alt="Logo" />
          <span class="forward-slash" style="font-size:35px ; color:#595f6a; margin-left: 5px;">/</span>
          <b>
            <span class="navbar-ip" id="navd">{{ip}}</span>
        </div>
      </nav>
    </header>
    <main>
      <b>
        <b>
          <b>
            <div id="popup" class="popup" style="display: block;">
              <h1 id="popup-title" style="color: rgb(241, 36, 36);">Error {{status}}</h1>
              <p id="popup-body" style="color: #918bca;">{{error_msg}}</p>
          </b>
          </div>
          <b></b>
        </b>
      </b>
      </b>
    </main>
  </body>
</html>

app/templates/smoke.html
<!DOCTYPE html>
<html>

<head>
  <title>CrowdSec</title>
  <link rel="preconnect" href="{{ q_get_app_base_url }}" crossorigin>
  <link rel="preload" href="{{ q_get_app_base_url }}static/fonts/Montserrat-Regular.ttf" as="font" type="font/ttf"
    crossorigin>
  <style>
    body {
      background-color: #1f2937;
      color: #fff;
      font-family: 'Montserrat', sans-serif;
      font-size: 16px;
      margin: 0;
      padding: 0;
    }

    @font-face {
      font-family: 'Montserrat';
      font-style: normal;
      font-weight: 400;
      font-display: swap;
      src: url('{{ q_get_app_base_url }}static/fonts/Montserrat-Regular.ttf');
    }

    /* fonts */
    #font {
      font-family: 'Montserrat', sans-serif;
    }

    .expand-view {
      display: inline-block;
      padding: 10px;
      cursor: pointer;
      background-color: #1f2937;

      position: unset;
      right: 50px;
    }

    .expand-view-arrow {
      display: inline-block;
      width: 0;
      height: 0;
      border-left: 10px solid transparent;
      border-right: 10px solid transparent;
      border-top: 10px solid #918bca;
      position: relative;
      right: 1px;
    }

    .collapse-view-arrow {
      display: inline-block;
      width: 0;
      height: 0;
      border-left: 10px solid transparent;
      border-right: 10px solid transparent;
      border-bottom: 10px solid #918bca;
      /* change to border-bottom */
      position: relative;
      top: 1px;
      /* change to top */
    }

    .navbar {
      background-color: #111827;
      height: 60px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 0 20px;
      position: relative;
      box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
    }

    .navbar::after {
      content: "";
      position: absolute;
      bottom: 0;
      left: 0;
      width: 100%;
      height: 2px;
      background-color: #252f3e;
    }

    .navbar-logo {
      height: 40px;
      width: auto;
    }

    .navbar-ip {
      margin-left: 10px;
      font-size: 25px;
    }

    .navbar-left {
      display: flex;
      align-items: center;
    }

    .container-header{
      margin-left: 8mm;
      margin-right:8mm;
      margin-top:13px ;
      color:#a3a7af ;
    }
    .navbar-score {
      font-size: 17px;
      display: inline-block;
      height: 5mm;
      border-radius: 5px;
    }

    .container {
      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: space-between;
      padding: 16px;
      margin-top: 10px;
      position: relative;
      box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.5);
    }

    .container2 {
      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: space-between;
      padding: 16px;
      padding-bottom: 4px;
      margin-top: 0px;
      box-shadow: 0px 0px 0px rgba(0, 0, 0, 0.5);
    }

    .range,
    .as,
    .known {
      margin-right: 20px;
    }

    .known-tag{
      color: rgb(155, 24, 188);
      border: 2px solid rgb(155, 24, 188);
      border-radius: 5px;
      padding: 4px;
      margin-right: 8px;
      margin-bottom: 3px;
      display: inline-block;
    }

    .bg-score {
      text-align: right;
      font-size: 20px;
    }

    .score-box-green {
      border: 2px solid rgb(28, 202, 28);
      padding: 10px;
      display: inline-block;
      color: rgb(34, 202, 34);
    }

    .score-box-yellow {
      border: 2px solid rgb(190, 218, 29);
      padding: 10px;
      display: inline-block;
      color: rgb(190, 218, 29);
    }

    .score-box-red {
      border: 2px solid rgb(191, 34, 34);
      padding: 10px;
      display: inline-block;
      color: rgb(191, 34, 34);
    }

    .category {
      border-left: 5px solid rgb(155, 24, 188);
      background-color: #1f2937;
      padding: 10px;
      margin-bottom: 10px;
      border-radius: 5px;
      color: #fff;
      margin-left: 8mm;
      margin-right: 8mm;
      border: 2px solid #283240 ;
      border-left: 4px solid #771ec0;
    }

    .category-header {
      color: #b2b6bd;
    }

    .category-p{
      color: #a6abb2;
    }

    .attackbox {
      border-left: 5px solid rgb(155, 24, 188);
      background-color: #1f2937;
      padding: 10px;
      margin-bottom: 10px;
      border-radius: 5px;
      color: #fff;
    }

    .category h3 {
      margin-top: 0;
      font-size: 18px;
      font-weight: bold;
      color: #f0eeee;
    }

    .category p {
      margin-bottom: 0;
      font-size: 14px;
      color: #969191;
    }

    .forward-slash {
      margin-left: 5px;
    }

    /*      */
    .inline {
      display: inline-block;
      vertical-align: middle;
    }

    .scroller {
      /* width: 300px; */
      max-height: 300px;
      overflow-y: scroll;

    }

    .scroller::-webkit-scrollbar {
      height: 12px;
      width: 12px;
      background: #918bca;
      border-radius: 5px;
    }

    .scroller::-webkit-scrollbar-thumb {
      background: #473cae;
      /* height: 40px; */
      /* width: 10px; */
      -webkit-border-radius: 1ex;
      -webkit-box-shadow: 0px 1px 2px #918bca;
    }

    .scroller::-webkit-scrollbar-corner {
      background: #1f2937;
    }
  </style>
</head>

<body>
  <header>
    <nav class="navbar">
      <div class="navbar-left">
        <img class="navbar-logo" src="{{ q_get_app_base_url }}static/crowdseclogo.png" alt="Logo" />
        <span class="forward-slash" style="font-size:35px ; color:#595f6a">/</span>
        <b>
          <span class="navbar-ip" id="navd"> {{data.ip}}</span>
      </div>
      <div class="navbar-right" style=" color: #616a77;">
        <span>Total Score: </span>
        <b>
          <span class='navbar-score {{ "score-box-green" if data.scores.overall.total <= 2 else "score-box-yellow" if data.scores.overall.total <= 3 else "score-box-red" }}' id="score-box" style=" font-family: 'Montserrat', sans-serif;">{{data.scores.overall.total}} / 5</span>
        </b>
      </div>
    </nav>
  </header>
  <main>
    <div class="super">
      <div class="container">
        <div class="left">
          <div class="range" style="font-family: 'Montserrat', sans-serif; color: #616a77">Range: <b>
              <span id="range" style="color:#e1e6ec"> {{ data.ip_range if data.ip_range else "N/A" }}</span>
              {% if data.ip_range_score %}
                <span id="ipscore" style="color:#616190">
                {% if data.ip_range_score <= 2 %}
                  - IP's range is not aggressive.
                {% elif data.ip_range_score <= 3 %}
                  - IP's range is moderately aggressive.
                {% else %}
                  - IP's range is very aggressive.
                {% endif %}
                </span>
              {% endif %}
          </div>
          <br />
          <div class="as" style=" color: #616a77">AS: <b>
              <span id="as" style="color:#e1e6ec">{{ data.as_name if data.as_name else "N/A" }}</span>
          </div>
          <br />
          <div class="known" style=" color: #616a77">Known for: <span id="known">
            {% for behaviour in data.behaviors %}
              <span class="known-tag">
                  {{ behaviour.label }}
              </span>
            {% endfor %}
          </span>
          </div>
        </div>
        <div class="right">
          <div class="vc" id="vc" style="text-align: right;">
            <a id="console-link" href="https://app.crowdsec.net/cti/{{data.ip}}" target="_blank" rel="noopener noreferrer"
              style=" position: relative;right: 1.5mm;color:#616190;">View In Console</a>
          </div>
          <br>
          <br>
          <br>
          <div class="bg-score" style=" font-size: medium; color: #616a77; "> Background noise score : <span
              class='navbar-score {{ "score-box-green" if data.background_noise_score <= 4 else "score-box-yellow" if data.background_noise_score <= 7 else "score-box-red" }}' id="bg"> {{data.background_noise_score}} / 10</span>
          </div>
        </div>
      </div>
      <div class="container2">
        <div style="margin-left: 4mm; margin-right:8mm; color: #dfe2e6">Raw Response (JSON) : <span class="inline">
            <button onclick="copyData()"
              style="background-color:#1f2937; border: 2px solid #785e29; color:#f0a71b; padding: 8px 16px; border-radius: 2mm; font-family: 'Montserrat', sans-serif; cursor:pointer"><b>Copy
                JSON</b></button></span></div>
        <div class="left"> <span id="expand-view" class="expand-view" onclick="toggleAccordion()">
            <span id="expand-view-text" style="color: #918bca; ">Show </span>
            <span id="expand-view-arrow" class="expand-view-arrow"></span>
          </span></p>
        </div>
      </div>
      <div>
        <div class="scroller" id="accordion" style="display: none;">
          <pre id="json-data" style="background-color: #1e293b; color: #dfe2e6; padding: 16px; border-radius: 4px;margin-top: 4px; border: 2px solid #4e6180; white-space: pre-wrap;
              max-width: 100%;
              overflow-x: auto;"></pre>
        </div>
      </div>
  </main>

  {% if data.classifications and data.classifications.classifications   %}
  <h2 class="container-header">Categories</h2>
  <div>
    {% for classification in data.classifications.classifications %}
    <div class="category">
      <h3 class="category-header">{{classification.label}}</h3>
      <p class="category-p">{{classification.description}}</p>
    </div>
    {% endfor %}
  </div>
  {% endif %}

  {% if data.attack_details %}
  <h2 class="container-header">Attack details</h2>
  <div>
    {% for attack_detail in data.attack_details %}
    <div class="category">
      <h3 class="category-header">{{attack_detail.label}}</h3>
      <p class="category-p">{{attack_detail.description}}</p>
    </div>
    {% endfor %}
  </div>
  {% endif %}

  {% if data.references %}
  <h2 class="container-header">References</h2>
  <div>
    {% for reference in data.references %}
    <div class="category">
      <h3 class="category-header">{{reference.label}}</h3>
      <p class="category-p">{{reference.description}}</p>
      {% for link in reference.references %}
      <p><a style="color:#616190" href="{{link}}">{{link}} </a></p>
      {% endfor %}
    </div>
    {% endfor %}
  </div>
  {% endif %}
  </div>
  <script>
    const data = JSON.parse('{{ data|tojson|safe }}');
    const toggleAccordion = () => {
      const accordion = document.getElementById("accordion");
      const arrow = document.getElementById("expand-view-arrow");
      const expandtxt = document.getElementById("expand-view-text");
      if (accordion.style.display === "none") {
        const jsonData = document.getElementById("json-data");
        jsonData.innerText = JSON.stringify(data, null, 2);
        accordion.style.display = "block";
        arrow.classList.remove("expand-view-arrow");
        arrow.classList.add("collapse-view-arrow");
        expandtxt.innerHTML = "Hide ";
      } else {
        accordion.style.display = "none";
        arrow.classList.remove("collapse-view-arrow");
        arrow.classList.add("expand-view-arrow");
        expandtxt.innerHTML = "Show ";

      }
    }

    const copyData = () => {
      const jsonString = JSON.stringify(data);
      navigator.clipboard.writeText(jsonString).then(() => {
        alert("JSON copied to clipboard!");
      }).catch(err => {
        console.error("Failed to copy JSON: ", err);
      });
    }
  </script>
</body>

</html>